// tslint:disable
/**
 * 社区生鲜
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AdFile
 */
export interface AdFile {
    /**
     * ID
     * @type {number}
     * @memberof AdFile
     */
    id?: number | null;
    /**
     * 文件名
     * @type {string}
     * @memberof AdFile
     */
    name: string;
    /**
     * 路径
     * @type {string}
     * @memberof AdFile
     */
    path: string;
    /**
     * 类型
     * @type {string}
     * @memberof AdFile
     */
    type: string;
    /**
     * 大小
     * @type {string}
     * @memberof AdFile
     */
    size: string;
    /**
     * 后缀
     * @type {string}
     * @memberof AdFile
     */
    suffix: string;
    /**
     * 域名
     * @type {string}
     * @memberof AdFile
     */
    domain: string;
    /**
     * 原文件名
     * @type {string}
     * @memberof AdFile
     */
    realName: string;
    /**
     * 创建时间
     * @type {string}
     * @memberof AdFile
     */
    createAt?: string | null;
}


