// tslint:disable
/**
 * 社区生鲜
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { AdRoleMenu } from './ad-role-menu';

/**
 * 
 * @export
 * @interface AdRoleMenuArrayVo
 */
export interface AdRoleMenuArrayVo {
    /**
     * 
     * @type {number}
     * @memberof AdRoleMenuArrayVo
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof AdRoleMenuArrayVo
     */
    msg?: string;
    /**
     * 
     * @type {Array<AdRoleMenu>}
     * @memberof AdRoleMenuArrayVo
     */
    data?: Array<AdRoleMenu>;
}


