// tslint:disable
/**
 * 社区生鲜
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AdRoleMenu
 */
export interface AdRoleMenu {
    /**
     * ID
     * @type {number}
     * @memberof AdRoleMenu
     */
    id?: number | null;
    /**
     * 角色id
     * @type {number}
     * @memberof AdRoleMenu
     */
    roleId: number;
    /**
     * 菜单id
     * @type {number}
     * @memberof AdRoleMenu
     */
    menuId: number;
    /**
     * 创建时间
     * @type {string}
     * @memberof AdRoleMenu
     */
    createAt?: string | null;
}


