// tslint:disable
/**
 * 社区生鲜
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AdUser
 */
export interface AdUser {
    /**
     * ID
     * @type {number}
     * @memberof AdUser
     */
    id?: number | null;
    /**
     * 用户名
     * @type {string}
     * @memberof AdUser
     */
    username: string;
    /**
     * 密码
     * @type {string}
     * @memberof AdUser
     */
    password: string;
    /**
     * 电话
     * @type {string}
     * @memberof AdUser
     */
    phone?: string | null;
    /**
     * 昵称
     * @type {string}
     * @memberof AdUser
     */
    nickname: string;
    /**
     * 头像地址
     * @type {string}
     * @memberof AdUser
     */
    avatar?: string | null;
    /**
     * 邮箱
     * @type {string}
     * @memberof AdUser
     */
    email?: string | null;
    /**
     * 是否能够删除
     * @type {boolean}
     * @memberof AdUser
     */
    isDel: boolean;
    /**
     * 部门名称
     * @type {string}
     * @memberof AdUser
     */
    deptName?: string | null;
    /**
     * 部门id
     * @type {number}
     * @memberof AdUser
     */
    deptId?: number | null;
    /**
     * 角色id
     * @type {number}
     * @memberof AdUser
     */
    roleId?: number | null;
    /**
     * 角色名称
     * @type {string}
     * @memberof AdUser
     */
    roleName?: string | null;
    /**
     * 1为正常，2为禁用
     * @type {number}
     * @memberof AdUser
     */
    status: number;
    /**
     * 创建时间
     * @type {string}
     * @memberof AdUser
     */
    createAt?: string | null;
    /**
     * 更新时间
     * @type {string}
     * @memberof AdUser
     */
    updateAt?: string | null;
}


