// tslint:disable
/**
 * 社区生鲜
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { FsCart } from './fs-cart';

/**
 * 
 * @export
 * @interface CartDto
 */
export interface CartDto {
    /**
     * 购物车数据
     * @type {Array<FsCart>}
     * @memberof CartDto
     */
    cart?: Array<FsCart>;
}


