// tslint:disable
/**
 * 社区生鲜
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CartVo
 */
export interface CartVo {
    /**
     * ID
     * @type {number}
     * @memberof CartVo
     */
    id?: number | null;
    /**
     * 门店id
     * @type {number}
     * @memberof CartVo
     */
    storeId: number;
    /**
     * 分类id
     * @type {number}
     * @memberof CartVo
     */
    cateId: number;
    /**
     * 商品名称
     * @type {string}
     * @memberof CartVo
     */
    name: string;
    /**
     * 商品图片
     * @type {string}
     * @memberof CartVo
     */
    image: string;
    /**
     * 轮播图（用,分割）
     * @type {string}
     * @memberof CartVo
     */
    swiper: string;
    /**
     * 商品简介
     * @type {string}
     * @memberof CartVo
     */
    introduction?: string | null;
    /**
     * 规格名称
     * @type {string}
     * @memberof CartVo
     */
    unit?: string | null;
    /**
     * 排序
     * @type {number}
     * @memberof CartVo
     */
    sort: number;
    /**
     * 储存方式
     * @type {string}
     * @memberof CartVo
     */
    storage?: string | null;
    /**
     * 生产日期
     * @type {string}
     * @memberof CartVo
     */
    pd?: string | null;
    /**
     * 保质期（天）
     * @type {number}
     * @memberof CartVo
     */
    exp?: number | null;
    /**
     * 关键词
     * @type {string}
     * @memberof CartVo
     */
    keyword?: string | null;
    /**
     * 条形码
     * @type {string}
     * @memberof CartVo
     */
    barcode?: string | null;
    /**
     * 商品价格
     * @type {string}
     * @memberof CartVo
     */
    price: string;
    /**
     * 市场价格
     * @type {string}
     * @memberof CartVo
     */
    originPrice: string;
    /**
     * 成本价
     * @type {string}
     * @memberof CartVo
     */
    cost?: string | null;
    /**
     * 销量
     * @type {number}
     * @memberof CartVo
     */
    sales: number;
    /**
     * 库存
     * @type {number}
     * @memberof CartVo
     */
    stock: number;
    /**
     * 状态，1上架、2下架
     * @type {number}
     * @memberof CartVo
     */
    status: number;
    /**
     * 商品详情
     * @type {string}
     * @memberof CartVo
     */
    description: string;
    /**
     * 浏览量
     * @type {number}
     * @memberof CartVo
     */
    browse: number;
    /**
     * 返回积分
     * @type {number}
     * @memberof CartVo
     */
    backIntegral: number;
    /**
     * 所需积分
     * @type {number}
     * @memberof CartVo
     */
    needIntegral?: number | null;
    /**
     * 是否限制时段
     * @type {number}
     * @memberof CartVo
     */
    isLimitTime: number;
    /**
     * 限制开始时间
     * @type {string}
     * @memberof CartVo
     */
    limitStartTime?: string | null;
    /**
     * 限制结束时间
     * @type {string}
     * @memberof CartVo
     */
    limitEndTime?: string | null;
    /**
     * 商品类型（普通商品，积分商品）
     * @type {number}
     * @memberof CartVo
     */
    type: number;
    /**
     * 创建时间
     * @type {string}
     * @memberof CartVo
     */
    createAt?: string | null;
    /**
     * 更新时间
     * @type {string}
     * @memberof CartVo
     */
    updateAt?: string | null;
    /**
     * 商品数量
     * @type {number}
     * @memberof CartVo
     */
    number?: number;
    /**
     * 标签
     * @type {Array<string>}
     * @memberof CartVo
     */
    label?: Array<string>;
}


