// tslint:disable
/**
 * 社区生鲜
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface DeptVo
 */
export interface DeptVo {
    /**
     * ID
     * @type {number}
     * @memberof DeptVo
     */
    id?: number | null;
    /**
     * 名称
     * @type {string}
     * @memberof DeptVo
     */
    name: string;
    /**
     * 部门描述
     * @type {string}
     * @memberof DeptVo
     */
    remark?: string | null;
    /**
     * 负责人
     * @type {string}
     * @memberof DeptVo
     */
    charge?: string | null;
    /**
     * 邮箱
     * @type {string}
     * @memberof DeptVo
     */
    email?: string | null;
    /**
     * 联系电话
     * @type {string}
     * @memberof DeptVo
     */
    phone?: string | null;
    /**
     * 上级部门
     * @type {number}
     * @memberof DeptVo
     */
    pid?: number | null;
    /**
     * 1为正常，2为禁用
     * @type {number}
     * @memberof DeptVo
     */
    status: number;
    /**
     * 创建时间
     * @type {string}
     * @memberof DeptVo
     */
    createAt?: string | null;
    /**
     * 更新时间
     * @type {string}
     * @memberof DeptVo
     */
    updateAt?: string | null;
    /**
     * 子节点
     * @type {Array<DeptVo>}
     * @memberof DeptVo
     */
    children?: Array<DeptVo>;
}


