// tslint:disable
/**
 * 社区生鲜
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { DeptVo } from './dept-vo';

/**
 * 
 * @export
 * @interface DeptPageVo
 */
export interface DeptPageVo {
    /**
     * 
     * @type {number}
     * @memberof DeptPageVo
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof DeptPageVo
     */
    msg?: string;
    /**
     * 
     * @type {Array<DeptVo>}
     * @memberof DeptPageVo
     */
    data?: Array<DeptVo>;
}


