// tslint:disable
/**
 * 社区生鲜
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface FsAddress
 */
export interface FsAddress {
    /**
     * ID
     * @type {number}
     * @memberof FsAddress
     */
    id?: number | null;
    /**
     * 商城用户id
     * @type {number}
     * @memberof FsAddress
     */
    userId?: number | null;
    /**
     * 收货人
     * @type {string}
     * @memberof FsAddress
     */
    receiver: string;
    /**
     * 联系电话
     * @type {string}
     * @memberof FsAddress
     */
    phone: string;
    /**
     * 标签
     * @type {string}
     * @memberof FsAddress
     */
    label?: string | null;
    /**
     * 纬度
     * @type {string}
     * @memberof FsAddress
     */
    latitude: string;
    /**
     * 经度
     * @type {string}
     * @memberof FsAddress
     */
    longitude: string;
    /**
     * 是否默认地址
     * @type {boolean}
     * @memberof FsAddress
     */
    isDefault: boolean;
    /**
     * 创建时间
     * @type {string}
     * @memberof FsAddress
     */
    createAt?: string | null;
    /**
     * 更新时间
     * @type {string}
     * @memberof FsAddress
     */
    updateAt?: string | null;
    /**
     * 地址
     * @type {string}
     * @memberof FsAddress
     */
    address: string;
    /**
     * 详细地址
     * @type {string}
     * @memberof FsAddress
     */
    addressDetail: string;
    /**
     * 名称
     * @type {string}
     * @memberof FsAddress
     */
    name: string;
}


