// tslint:disable
/**
 * 社区生鲜
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { FsCart } from './fs-cart';

/**
 * 
 * @export
 * @interface FsCartArrayVo
 */
export interface FsCartArrayVo {
    /**
     * 
     * @type {number}
     * @memberof FsCartArrayVo
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof FsCartArrayVo
     */
    msg?: string;
    /**
     * 
     * @type {Array<FsCart>}
     * @memberof FsCartArrayVo
     */
    data?: Array<FsCart>;
}


