// tslint:disable
/**
 * 社区生鲜
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface FsCart
 */
export interface FsCart {
    /**
     * ID
     * @type {number}
     * @memberof FsCart
     */
    id?: number | null;
    /**
     * 用户id
     * @type {number}
     * @memberof FsCart
     */
    userId?: number | null;
    /**
     * 商品id
     * @type {number}
     * @memberof FsCart
     */
    goodsId: number;
    /**
     * 门店id
     * @type {number}
     * @memberof FsCart
     */
    storeId: number;
    /**
     * 购物车来源，1APP商城、2人工收银台、3自助收银台
     * @type {number}
     * @memberof FsCart
     */
    origin: number;
    /**
     * 商品名称
     * @type {string}
     * @memberof FsCart
     */
    name: string;
    /**
     * 商品数量
     * @type {number}
     * @memberof FsCart
     */
    number: number;
    /**
     * 商品图片
     * @type {string}
     * @memberof FsCart
     */
    image: string;
    /**
     * 创建时间
     * @type {string}
     * @memberof FsCart
     */
    createAt?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FsCart
     */
    updateAt?: string | null;
}


