// tslint:disable
/**
 * 社区生鲜
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { FsGoodsCate } from './fs-goods-cate';

/**
 * 
 * @export
 * @interface FsGoodsCateVo
 */
export interface FsGoodsCateVo {
    /**
     * 
     * @type {number}
     * @memberof FsGoodsCateVo
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof FsGoodsCateVo
     */
    msg?: string;
    /**
     * 
     * @type {FsGoodsCate}
     * @memberof FsGoodsCateVo
     */
    data?: FsGoodsCate;
}


