// tslint:disable
/**
 * 社区生鲜
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { FsGoodsLabel } from './fs-goods-label';

/**
 * 
 * @export
 * @interface FsGoodsLabelVo
 */
export interface FsGoodsLabelVo {
    /**
     * 
     * @type {number}
     * @memberof FsGoodsLabelVo
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof FsGoodsLabelVo
     */
    msg?: string;
    /**
     * 
     * @type {FsGoodsLabel}
     * @memberof FsGoodsLabelVo
     */
    data?: FsGoodsLabel;
}


