// tslint:disable
/**
 * 社区生鲜
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface FsGift
 */
export interface FsGift {
    /**
     * ID
     * @type {number}
     * @memberof FsGift
     */
    id?: number | null;
    /**
     * 用户id
     * @type {number}
     * @memberof FsGift
     */
    userId: number;
    /**
     * 赠送余额
     * @type {string}
     * @memberof FsGift
     */
    balance: string;
    /**
     * 赠送积分
     * @type {string}
     * @memberof FsGift
     */
    integral: string;
    /**
     * 备注
     * @type {string}
     * @memberof FsGift
     */
    remark: string;
    /**
     * 创建时间
     * @type {string}
     * @memberof FsGift
     */
    createAt?: string | null;
    /**
     * 更新时间
     * @type {string}
     * @memberof FsGift
     */
    updateAt?: string | null;
}


