// tslint:disable
/**
 * 社区生鲜
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { FsGoods } from './fs-goods';

/**
 * 
 * @export
 * @interface FsGoodsPageVo
 */
export interface FsGoodsPageVo {
    /**
     * 
     * @type {number}
     * @memberof FsGoodsPageVo
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof FsGoodsPageVo
     */
    msg?: string;
    /**
     * 
     * @type {number}
     * @memberof FsGoodsPageVo
     */
    page?: number;
    /**
     * 
     * @type {number}
     * @memberof FsGoodsPageVo
     */
    pageSize?: number;
    /**
     * 
     * @type {number}
     * @memberof FsGoodsPageVo
     */
    totalCount?: number;
    /**
     * 
     * @type {Array<FsGoods>}
     * @memberof FsGoodsPageVo
     */
    data?: Array<FsGoods>;
}


