// tslint:disable
/**
 * 社区生鲜
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { FsLabelGoods } from './fs-label-goods';

/**
 * 
 * @export
 * @interface FsLabelGoodsArrayVo
 */
export interface FsLabelGoodsArrayVo {
    /**
     * 
     * @type {number}
     * @memberof FsLabelGoodsArrayVo
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof FsLabelGoodsArrayVo
     */
    msg?: string;
    /**
     * 
     * @type {Array<FsLabelGoods>}
     * @memberof FsLabelGoodsArrayVo
     */
    data?: Array<FsLabelGoods>;
}


