// tslint:disable
/**
 * 社区生鲜
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { FsOrder } from './fs-order';

/**
 * 
 * @export
 * @interface FsOrderPageVo
 */
export interface FsOrderPageVo {
    /**
     * 
     * @type {number}
     * @memberof FsOrderPageVo
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof FsOrderPageVo
     */
    msg?: string;
    /**
     * 
     * @type {number}
     * @memberof FsOrderPageVo
     */
    page?: number;
    /**
     * 
     * @type {number}
     * @memberof FsOrderPageVo
     */
    pageSize?: number;
    /**
     * 
     * @type {number}
     * @memberof FsOrderPageVo
     */
    totalCount?: number;
    /**
     * 
     * @type {Array<FsOrder>}
     * @memberof FsOrderPageVo
     */
    data?: Array<FsOrder>;
}


