// tslint:disable
/**
 * 社区生鲜
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { FsOrder } from './fs-order';

/**
 * 
 * @export
 * @interface FsOrderVo
 */
export interface FsOrderVo {
    /**
     * 
     * @type {number}
     * @memberof FsOrderVo
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof FsOrderVo
     */
    msg?: string;
    /**
     * 
     * @type {FsOrder}
     * @memberof FsOrderVo
     */
    data?: FsOrder;
}


