// tslint:disable
/**
 * 社区生鲜
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface FsRecharge
 */
export interface FsRecharge {
    /**
     * ID
     * @type {number}
     * @memberof FsRecharge
     */
    id?: number | null;
    /**
     * 名称
     * @type {string}
     * @memberof FsRecharge
     */
    name: string;
    /**
     * 价格
     * @type {string}
     * @memberof FsRecharge
     */
    price: string;
    /**
     * 到账余额
     * @type {string}
     * @memberof FsRecharge
     */
    balance: string;
    /**
     * 备注
     * @type {string}
     * @memberof FsRecharge
     */
    remark?: string | null;
    /**
     * 创建时间
     * @type {string}
     * @memberof FsRecharge
     */
    createAt?: string | null;
    /**
     * 更新时间
     * @type {string}
     * @memberof FsRecharge
     */
    updateAt?: string | null;
}


