// tslint:disable
/**
 * 社区生鲜
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { FsRecharge } from './fs-recharge';

/**
 * 
 * @export
 * @interface FsRechargeArrayVo
 */
export interface FsRechargeArrayVo {
    /**
     * 
     * @type {number}
     * @memberof FsRechargeArrayVo
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof FsRechargeArrayVo
     */
    msg?: string;
    /**
     * 
     * @type {Array<FsRecharge>}
     * @memberof FsRechargeArrayVo
     */
    data?: Array<FsRecharge>;
}


