// tslint:disable
/**
 * 社区生鲜
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface FsSwiper
 */
export interface FsSwiper {
    /**
     * 
     * @type {number}
     * @memberof FsSwiper
     */
    id?: number | null;
    /**
     * 排序
     * @type {number}
     * @memberof FsSwiper
     */
    sort: number;
    /**
     * 图片地址
     * @type {string}
     * @memberof FsSwiper
     */
    image: string;
    /**
     * 跳转类型，0为应用、1为外链
     * @type {number}
     * @memberof FsSwiper
     */
    type: number;
    /**
     * 应用页面地址，或外链
     * @type {string}
     * @memberof FsSwiper
     */
    url?: string | null;
    /**
     * 标题
     * @type {string}
     * @memberof FsSwiper
     */
    title?: string | null;
    /**
     * 1为正常，2为禁用
     * @type {number}
     * @memberof FsSwiper
     */
    status: number;
    /**
     * 创建时间
     * @type {string}
     * @memberof FsSwiper
     */
    createAt?: string | null;
    /**
     * 更新时间
     * @type {string}
     * @memberof FsSwiper
     */
    updateAt?: string | null;
}


