// tslint:disable
/**
 * 社区生鲜
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface FsStock
 */
export interface FsStock {
    /**
     * ID
     * @type {number}
     * @memberof FsStock
     */
    id?: number | null;
    /**
     * 商品id
     * @type {number}
     * @memberof FsStock
     */
    goodsId: number;
    /**
     * 进货、出货量
     * @type {number}
     * @memberof FsStock
     */
    number: number;
    /**
     * 类型，0进货、1出货
     * @type {number}
     * @memberof FsStock
     */
    type: number;
    /**
     * 备注
     * @type {string}
     * @memberof FsStock
     */
    remark?: string | null;
    /**
     * 创建时间
     * @type {string}
     * @memberof FsStock
     */
    createAt?: string | null;
    /**
     * 更新时间
     * @type {string}
     * @memberof FsStock
     */
    updateAt?: string | null;
}


