// tslint:disable
/**
 * 社区生鲜
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { FsSwiper } from './fs-swiper';

/**
 * 
 * @export
 * @interface FsSwiperArrayVo
 */
export interface FsSwiperArrayVo {
    /**
     * 
     * @type {number}
     * @memberof FsSwiperArrayVo
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof FsSwiperArrayVo
     */
    msg?: string;
    /**
     * 
     * @type {Array<FsSwiper>}
     * @memberof FsSwiperArrayVo
     */
    data?: Array<FsSwiper>;
}


