// tslint:disable
/**
 * 社区生鲜
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { FsUser } from './fs-user';

/**
 * 
 * @export
 * @interface FsUserVo
 */
export interface FsUserVo {
    /**
     * 
     * @type {number}
     * @memberof FsUserVo
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof FsUserVo
     */
    msg?: string;
    /**
     * 
     * @type {FsUser}
     * @memberof FsUserVo
     */
    data?: FsUser;
}


