// tslint:disable
/**
 * 社区生鲜
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface FsUser
 */
export interface FsUser {
    /**
     * ID
     * @type {number}
     * @memberof FsUser
     */
    id?: number | null;
    /**
     * openid
     * @type {string}
     * @memberof FsUser
     */
    openid: string;
    /**
     * unionId
     * @type {string}
     * @memberof FsUser
     */
    unionId?: string | null;
    /**
     * appid
     * @type {string}
     * @memberof FsUser
     */
    appid: string;
    /**
     * 昵称
     * @type {string}
     * @memberof FsUser
     */
    nickName: string;
    /**
     * 头像地址
     * @type {string}
     * @memberof FsUser
     */
    avatarUrl?: string | null;
    /**
     * 手机号码
     * @type {string}
     * @memberof FsUser
     */
    phoneNumber: string;
    /**
     * 性别，1为男，0为女
     * @type {number}
     * @memberof FsUser
     */
    gender: number;
    /**
     * 积分
     * @type {number}
     * @memberof FsUser
     */
    integral: number;
    /**
     * 余额
     * @type {string}
     * @memberof FsUser
     */
    balance: string;
    /**
     * 状态，1为正常、2为禁用
     * @type {number}
     * @memberof FsUser
     */
    status: number;
    /**
     * 创建时间
     * @type {string}
     * @memberof FsUser
     */
    createAt?: string | null;
    /**
     * 更新时间
     * @type {string}
     * @memberof FsUser
     */
    updateAt?: string | null;
}


