// tslint:disable
/**
 * 社区生鲜
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { FsGoods } from './fs-goods';
import { FsGoodsLabel } from './fs-goods-label';

/**
 * 
 * @export
 * @interface Goods
 */
export interface Goods {
    /**
     * 商品信息
     * @type {FsGoods}
     * @memberof Goods
     */
    goods: FsGoods;
    /**
     * 标签信息
     * @type {Array<FsGoodsLabel>}
     * @memberof Goods
     */
    label: Array<FsGoodsLabel>;
}


