// tslint:disable
/**
 * 社区生鲜
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { Goods } from './goods';

/**
 * 
 * @export
 * @interface GoodsArrayVo
 */
export interface GoodsArrayVo {
    /**
     * 
     * @type {number}
     * @memberof GoodsArrayVo
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof GoodsArrayVo
     */
    msg?: string;
    /**
     * 
     * @type {number}
     * @memberof GoodsArrayVo
     */
    page?: number;
    /**
     * 
     * @type {number}
     * @memberof GoodsArrayVo
     */
    pageSize?: number;
    /**
     * 
     * @type {number}
     * @memberof GoodsArrayVo
     */
    totalCount?: number;
    /**
     * 商品信息
     * @type {Array<Goods>}
     * @memberof GoodsArrayVo
     */
    data: Array<Goods>;
}


