// tslint:disable
/**
 * 社区生鲜
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface MetaVo
 */
export interface MetaVo {
    /**
     * 
     * @type {string}
     * @memberof MetaVo
     */
    icon?: string;
    /**
     * 
     * @type {boolean}
     * @memberof MetaVo
     */
    isAffix?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof MetaVo
     */
    isHide?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof MetaVo
     */
    isIframe?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof MetaVo
     */
    isKeepAlive?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof MetaVo
     */
    isLink?: boolean;
    /**
     * 
     * @type {string}
     * @memberof MetaVo
     */
    title?: string;
}


