// tslint:disable
/**
 * 社区生鲜
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { OrderItem } from './order-item';

/**
 * 
 * @export
 * @interface OrderDto
 */
export interface OrderDto {
    /**
     * 门店id
     * @type {number}
     * @memberof OrderDto
     */
    storeId: number;
    /**
     * 收货人
     * @type {string}
     * @memberof OrderDto
     */
    consignee: string;
    /**
     * 地址
     * @type {string}
     * @memberof OrderDto
     */
    address: string;
    /**
     * 联系电话
     * @type {string}
     * @memberof OrderDto
     */
    phone: string;
    /**
     * 配送时间
     * @type {string}
     * @memberof OrderDto
     */
    distributionTime: string;
    /**
     * 支付方式，如微信支付、现金支付、余额支付、积分支付等
     * @type {string}
     * @memberof OrderDto
     */
    payType: string;
    /**
     * 送货方式，1门店配送、2到店自提、3第三方配送
     * @type {number}
     * @memberof OrderDto
     */
    deliveryType: number;
    /**
     * 订单来源，1小程序商城、2人工收银台、3自助收银台
     * @type {number}
     * @memberof OrderDto
     */
    origin: number;
    /**
     * 订单备注
     * @type {string}
     * @memberof OrderDto
     */
    mark?: string | null;
    /**
     * 订单项目
     * @type {Array<OrderItem>}
     * @memberof OrderDto
     */
    item: Array<OrderItem>;
}


