// tslint:disable
/**
 * 社区生鲜
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { TotalVo } from './total-vo';

/**
 * 
 * @export
 * @interface OrderTotalVo
 */
export interface OrderTotalVo {
    /**
     * 
     * @type {number}
     * @memberof OrderTotalVo
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof OrderTotalVo
     */
    msg?: string;
    /**
     * 订单统计数据
     * @type {TotalVo}
     * @memberof OrderTotalVo
     */
    data: TotalVo;
}


