// tslint:disable
/**
 * 社区生鲜
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface OrderRefundDto
 */
export interface OrderRefundDto {
    /**
     * 订单id
     * @type {number}
     * @memberof OrderRefundDto
     */
    id: number;
    /**
     * 退款金额
     * @type {number}
     * @memberof OrderRefundDto
     */
    refundPrice: number;
}


