// tslint:disable
/**
 * 社区生鲜
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface OrderItem
 */
export interface OrderItem {
    /**
     * 商品id
     * @type {number}
     * @memberof OrderItem
     */
    id: number;
    /**
     * 商品数量
     * @type {number}
     * @memberof OrderItem
     */
    number: number;
}


