// tslint:disable
/**
 * 社区生鲜
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface OrderDeliveryDto
 */
export interface OrderDeliveryDto {
    /**
     * 订单id
     * @type {number}
     * @memberof OrderDeliveryDto
     */
    id: number;
    /**
     * 配送员id
     * @type {number}
     * @memberof OrderDeliveryDto
     */
    dispatcherId: number;
    /**
     * 配送员姓名
     * @type {string}
     * @memberof OrderDeliveryDto
     */
    dispatcherName: string;
}


