// tslint:disable
/**
 * 社区生鲜
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { OrderAndItemVo } from './order-and-item-vo';

/**
 * 
 * @export
 * @interface OrderDetailVo
 */
export interface OrderDetailVo {
    /**
     * 
     * @type {number}
     * @memberof OrderDetailVo
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof OrderDetailVo
     */
    msg?: string;
    /**
     * 订单详情
     * @type {OrderAndItemVo}
     * @memberof OrderDetailVo
     */
    data: OrderAndItemVo;
}


