// tslint:disable
/**
 * 社区生鲜
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { OrderAndItemVo } from './order-and-item-vo';

/**
 * 
 * @export
 * @interface OrderDetailPageVo
 */
export interface OrderDetailPageVo {
    /**
     * 
     * @type {number}
     * @memberof OrderDetailPageVo
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof OrderDetailPageVo
     */
    msg?: string;
    /**
     * 
     * @type {number}
     * @memberof OrderDetailPageVo
     */
    page?: number;
    /**
     * 
     * @type {number}
     * @memberof OrderDetailPageVo
     */
    pageSize?: number;
    /**
     * 
     * @type {number}
     * @memberof OrderDetailPageVo
     */
    totalCount?: number;
    /**
     * 订单详情
     * @type {Array<OrderAndItemVo>}
     * @memberof OrderDetailPageVo
     */
    data: Array<OrderAndItemVo>;
}


