// tslint:disable
/**
 * 社区生鲜
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface RoleMenuDto
 */
export interface RoleMenuDto {
    /**
     * 角色id
     * @type {number}
     * @memberof RoleMenuDto
     */
    roleId: number;
    /**
     * 菜单id集合
     * @type {Array<number>}
     * @memberof RoleMenuDto
     */
    ids: Array<number>;
}


