// tslint:disable
/**
 * 社区生鲜
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { Store } from './store';

/**
 * 
 * @export
 * @interface StorePageVo
 */
export interface StorePageVo {
    /**
     * 
     * @type {number}
     * @memberof StorePageVo
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof StorePageVo
     */
    msg?: string;
    /**
     * 门店数据
     * @type {Array<Store>}
     * @memberof StorePageVo
     */
    data: Array<Store>;
}


