// tslint:disable
/**
 * 社区生鲜
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface TotalVo
 */
export interface TotalVo {
    /**
     * 待付款
     * @type {number}
     * @memberof TotalVo
     */
    watingPay: number;
    /**
     * 待发货
     * @type {number}
     * @memberof TotalVo
     */
    waitingDeliver: number;
    /**
     * 待发货
     * @type {number}
     * @memberof TotalVo
     */
    waitingReceipt: number;
    /**
     * 已完成
     * @type {number}
     * @memberof TotalVo
     */
    completed: number;
    /**
     * 退款/售后
     * @type {number}
     * @memberof TotalVo
     */
    refund: number;
}


