// tslint:disable
/**
 * 社区生鲜
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { UserLoginDataVo } from './user-login-data-vo';

/**
 * 
 * @export
 * @interface UserLoginVo
 */
export interface UserLoginVo {
    /**
     * 
     * @type {number}
     * @memberof UserLoginVo
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof UserLoginVo
     */
    msg?: string;
    /**
     * 
     * @type {UserLoginDataVo}
     * @memberof UserLoginVo
     */
    data?: UserLoginDataVo;
}


