/**
 * 社区生鲜
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';

export class AdFile {
    /**
    * ID
    */
    'id'?: number | null;
    /**
    * 文件名
    */
    'name': string;
    /**
    * 路径
    */
    'path': string;
    /**
    * 类型
    */
    'type': string;
    /**
    * 大小
    */
    'size': string;
    /**
    * 后缀
    */
    'suffix': string;
    /**
    * 域名
    */
    'domain': string;
    /**
    * 原文件名
    */
    'realName': string;
    /**
    * 创建时间
    */
    'createAt'?: Date | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "path",
            "baseName": "path",
            "type": "string"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "string"
        },
        {
            "name": "size",
            "baseName": "size",
            "type": "string"
        },
        {
            "name": "suffix",
            "baseName": "suffix",
            "type": "string"
        },
        {
            "name": "domain",
            "baseName": "domain",
            "type": "string"
        },
        {
            "name": "realName",
            "baseName": "realName",
            "type": "string"
        },
        {
            "name": "createAt",
            "baseName": "createAt",
            "type": "Date"
        }    ];

    static getAttributeTypeMap() {
        return AdFile.attributeTypeMap;
    }
}

