/**
 * 社区生鲜
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';

export class DeptVo {
    /**
    * ID
    */
    'id'?: number | null;
    /**
    * 名称
    */
    'name': string;
    /**
    * 部门描述
    */
    'remark'?: string | null;
    /**
    * 负责人
    */
    'charge'?: string | null;
    /**
    * 邮箱
    */
    'email'?: string | null;
    /**
    * 联系电话
    */
    'phone'?: string | null;
    /**
    * 上级部门
    */
    'pid'?: number | null;
    /**
    * 1为正常，2为禁用
    */
    'status': number;
    /**
    * 创建时间
    */
    'createAt'?: Date | null;
    /**
    * 更新时间
    */
    'updateAt'?: Date | null;
    /**
    * 子节点
    */
    'children'?: Array<DeptVo>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "remark",
            "baseName": "remark",
            "type": "string"
        },
        {
            "name": "charge",
            "baseName": "charge",
            "type": "string"
        },
        {
            "name": "email",
            "baseName": "email",
            "type": "string"
        },
        {
            "name": "phone",
            "baseName": "phone",
            "type": "string"
        },
        {
            "name": "pid",
            "baseName": "pid",
            "type": "number"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "number"
        },
        {
            "name": "createAt",
            "baseName": "createAt",
            "type": "Date"
        },
        {
            "name": "updateAt",
            "baseName": "updateAt",
            "type": "Date"
        },
        {
            "name": "children",
            "baseName": "children",
            "type": "Array<DeptVo>"
        }    ];

    static getAttributeTypeMap() {
        return DeptVo.attributeTypeMap;
    }
}

