/**
 * 社区生鲜
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';

export class FsCart {
    /**
    * ID
    */
    'id'?: number | null;
    /**
    * 用户id
    */
    'userId'?: number | null;
    /**
    * 商品id
    */
    'goodsId': number;
    /**
    * 门店id
    */
    'storeId': number;
    /**
    * 购物车来源，1APP商城、2人工收银台、3自助收银台
    */
    'origin': number;
    /**
    * 商品名称
    */
    'name': string;
    /**
    * 商品数量
    */
    'number': number;
    /**
    * 商品图片
    */
    'image': string;
    /**
    * 创建时间
    */
    'createAt'?: Date | null;
    'updateAt'?: Date | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "userId",
            "baseName": "userId",
            "type": "number"
        },
        {
            "name": "goodsId",
            "baseName": "goodsId",
            "type": "number"
        },
        {
            "name": "storeId",
            "baseName": "storeId",
            "type": "number"
        },
        {
            "name": "origin",
            "baseName": "origin",
            "type": "number"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "number",
            "baseName": "number",
            "type": "number"
        },
        {
            "name": "image",
            "baseName": "image",
            "type": "string"
        },
        {
            "name": "createAt",
            "baseName": "createAt",
            "type": "Date"
        },
        {
            "name": "updateAt",
            "baseName": "updateAt",
            "type": "Date"
        }    ];

    static getAttributeTypeMap() {
        return FsCart.attributeTypeMap;
    }
}

