/**
 * 社区生鲜
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';

export class FsGoods {
    /**
    * ID
    */
    'id'?: number | null;
    /**
    * 门店id
    */
    'storeId': number;
    /**
    * 分类id
    */
    'cateId': number;
    /**
    * 商品名称
    */
    'name': string;
    /**
    * 商品图片
    */
    'image': string;
    /**
    * 轮播图（用,分割）
    */
    'swiper': string;
    /**
    * 商品简介
    */
    'introduction'?: string | null;
    /**
    * 规格名称
    */
    'unit'?: string | null;
    /**
    * 排序
    */
    'sort': number;
    /**
    * 储存方式
    */
    'storage'?: string | null;
    /**
    * 生产日期
    */
    'pd'?: string | null;
    /**
    * 保质期（天）
    */
    'exp'?: number | null;
    /**
    * 关键词
    */
    'keyword'?: string | null;
    /**
    * 条形码
    */
    'barcode'?: string | null;
    /**
    * 商品价格
    */
    'price': string;
    /**
    * 市场价格
    */
    'originPrice': string;
    /**
    * 成本价
    */
    'cost'?: string | null;
    /**
    * 销量
    */
    'sales': number;
    /**
    * 库存
    */
    'stock': number;
    /**
    * 状态，1上架、2下架
    */
    'status': number;
    /**
    * 商品详情
    */
    'description': string;
    /**
    * 浏览量
    */
    'browse': number;
    /**
    * 返回积分
    */
    'backIntegral': number;
    /**
    * 所需积分
    */
    'needIntegral'?: number | null;
    /**
    * 是否限制时段
    */
    'isLimitTime': number;
    /**
    * 限制开始时间
    */
    'limitStartTime'?: Date | null;
    /**
    * 限制结束时间
    */
    'limitEndTime'?: Date | null;
    /**
    * 商品类型（普通商品，积分商品）
    */
    'type': number;
    /**
    * 创建时间
    */
    'createAt'?: Date | null;
    /**
    * 更新时间
    */
    'updateAt'?: Date | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "storeId",
            "baseName": "storeId",
            "type": "number"
        },
        {
            "name": "cateId",
            "baseName": "cateId",
            "type": "number"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "image",
            "baseName": "image",
            "type": "string"
        },
        {
            "name": "swiper",
            "baseName": "swiper",
            "type": "string"
        },
        {
            "name": "introduction",
            "baseName": "introduction",
            "type": "string"
        },
        {
            "name": "unit",
            "baseName": "unit",
            "type": "string"
        },
        {
            "name": "sort",
            "baseName": "sort",
            "type": "number"
        },
        {
            "name": "storage",
            "baseName": "storage",
            "type": "string"
        },
        {
            "name": "pd",
            "baseName": "pd",
            "type": "string"
        },
        {
            "name": "exp",
            "baseName": "exp",
            "type": "number"
        },
        {
            "name": "keyword",
            "baseName": "keyword",
            "type": "string"
        },
        {
            "name": "barcode",
            "baseName": "barcode",
            "type": "string"
        },
        {
            "name": "price",
            "baseName": "price",
            "type": "string"
        },
        {
            "name": "originPrice",
            "baseName": "originPrice",
            "type": "string"
        },
        {
            "name": "cost",
            "baseName": "cost",
            "type": "string"
        },
        {
            "name": "sales",
            "baseName": "sales",
            "type": "number"
        },
        {
            "name": "stock",
            "baseName": "stock",
            "type": "number"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "number"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "browse",
            "baseName": "browse",
            "type": "number"
        },
        {
            "name": "backIntegral",
            "baseName": "backIntegral",
            "type": "number"
        },
        {
            "name": "needIntegral",
            "baseName": "needIntegral",
            "type": "number"
        },
        {
            "name": "isLimitTime",
            "baseName": "isLimitTime",
            "type": "number"
        },
        {
            "name": "limitStartTime",
            "baseName": "limitStartTime",
            "type": "Date"
        },
        {
            "name": "limitEndTime",
            "baseName": "limitEndTime",
            "type": "Date"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "number"
        },
        {
            "name": "createAt",
            "baseName": "createAt",
            "type": "Date"
        },
        {
            "name": "updateAt",
            "baseName": "updateAt",
            "type": "Date"
        }    ];

    static getAttributeTypeMap() {
        return FsGoods.attributeTypeMap;
    }
}

