/**
 * 社区生鲜
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';

export class FsGoodsCate {
    /**
    * ID
    */
    'id'?: number | null;
    /**
    * 父类id
    */
    'pid'?: number | null;
    /**
    * 分类名称
    */
    'name': string;
    /**
    * 图标
    */
    'icon'?: string | null;
    /**
    * 排序
    */
    'sort': number;
    /**
    * 是否在APP显示
    */
    'isShow': boolean;
    /**
    * 创建时间
    */
    'createAt'?: Date | null;
    /**
    * 更新时间
    */
    'updateAt'?: Date | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "pid",
            "baseName": "pid",
            "type": "number"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "icon",
            "baseName": "icon",
            "type": "string"
        },
        {
            "name": "sort",
            "baseName": "sort",
            "type": "number"
        },
        {
            "name": "isShow",
            "baseName": "isShow",
            "type": "boolean"
        },
        {
            "name": "createAt",
            "baseName": "createAt",
            "type": "Date"
        },
        {
            "name": "updateAt",
            "baseName": "updateAt",
            "type": "Date"
        }    ];

    static getAttributeTypeMap() {
        return FsGoodsCate.attributeTypeMap;
    }
}

