/**
 * 社区生鲜
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';

export class FsGoodsLabel {
    /**
    * ID
    */
    'id'?: number | null;
    /**
    * 标签名称
    */
    'name': string;
    /**
    * 创建时间
    */
    'createAt'?: Date | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "createAt",
            "baseName": "createAt",
            "type": "Date"
        }    ];

    static getAttributeTypeMap() {
        return FsGoodsLabel.attributeTypeMap;
    }
}

