/**
 * 社区生鲜
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';

export class FsOrderItem {
    /**
    * ID
    */
    'id'?: number | null;
    /**
    * 订单id
    */
    'orderId': number;
    /**
    * 商品id
    */
    'goodsId'?: number | null;
    /**
    * 商品名称
    */
    'name': string;
    /**
    * 商品价格
    */
    'price': string;
    /**
    * 数量
    */
    'number': number;
    /**
    * 图片地址
    */
    'image': string;
    /**
    * 退款数量
    */
    'refundNumber': number;
    /**
    * 退款状态，1未退款、2申请中、3已退款
    */
    'refundStatus': number;
    /**
    * 创建时间
    */
    'createAt'?: Date | null;
    /**
    * 更新时间
    */
    'updateAt'?: Date | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "orderId",
            "baseName": "orderId",
            "type": "number"
        },
        {
            "name": "goodsId",
            "baseName": "goodsId",
            "type": "number"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "price",
            "baseName": "price",
            "type": "string"
        },
        {
            "name": "number",
            "baseName": "number",
            "type": "number"
        },
        {
            "name": "image",
            "baseName": "image",
            "type": "string"
        },
        {
            "name": "refundNumber",
            "baseName": "refundNumber",
            "type": "number"
        },
        {
            "name": "refundStatus",
            "baseName": "refundStatus",
            "type": "number"
        },
        {
            "name": "createAt",
            "baseName": "createAt",
            "type": "Date"
        },
        {
            "name": "updateAt",
            "baseName": "updateAt",
            "type": "Date"
        }    ];

    static getAttributeTypeMap() {
        return FsOrderItem.attributeTypeMap;
    }
}

