/**
 * 社区生鲜
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';

export class FsOrder {
    /**
    * ID
    */
    'id'?: number | null;
    /**
    * 订单号
    */
    'orderNumber': string;
    /**
    * 额外订单号
    */
    'extendNumber'?: string | null;
    /**
    * 用户id
    */
    'userId'?: number | null;
    /**
    * 用户名称
    */
    'userName'?: string | null;
    /**
    * 门店id
    */
    'storeId'?: number | null;
    /**
    * 门店名称
    */
    'storeName'?: string | null;
    /**
    * 配送员id
    */
    'dispatcherId'?: number | null;
    /**
    * 配送员姓名
    */
    'dispatcherName'?: string | null;
    /**
    * 联系电话
    */
    'phone'?: string | null;
    /**
    * 地址
    */
    'address'?: string | null;
    /**
    * 收货人
    */
    'consignee'?: string | null;
    /**
    * 商品总数
    */
    'totalNum': number;
    /**
    * 商品总价
    */
    'totalPrice': string;
    /**
    * 是否已支付
    */
    'isPaid': boolean;
    /**
    * 返回积分
    */
    'backIntegral': number;
    /**
    * 支付时间
    */
    'payTime'?: Date | null;
    /**
    * 支付方式，如微信支付、现金支付、余额支付、积分支付等
    */
    'payType': string;
    /**
    * 订单来源，1小程序商城、2人工收银台、3自助收银台
    */
    'origin': number;
    /**
    * 订单状态，1待发货、2待收货、3已完成、4申请退款、5已退款、6已取消
    */
    'status': number;
    /**
    * 退款图片（用,分割）
    */
    'refundImage'?: string | null;
    /**
    * 退款原因
    */
    'refundReason'?: string | null;
    /**
    * 拒绝退款理由
    */
    'refundRefuse'?: string | null;
    /**
    * 退款时间
    */
    'refundTime'?: Date | null;
    /**
    * 退款金额
    */
    'refundPrice'?: string | null;
    /**
    * 订单类型，1商品、2充值
    */
    'orderType': number;
    /**
    * 充值金额
    */
    'chargePrice'?: string | null;
    /**
    * 订单备注
    */
    'mark'?: string | null;
    /**
    * 送货方式，1门店配送、2到店自提、3第三方配送
    */
    'deliveryType'?: number | null;
    /**
    * 配送时间
    */
    'distributionTime'?: Date | null;
    /**
    * 创建时间
    */
    'createAt'?: Date | null;
    /**
    * 更新时间
    */
    'updateAt'?: Date | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "orderNumber",
            "baseName": "orderNumber",
            "type": "string"
        },
        {
            "name": "extendNumber",
            "baseName": "extendNumber",
            "type": "string"
        },
        {
            "name": "userId",
            "baseName": "userId",
            "type": "number"
        },
        {
            "name": "userName",
            "baseName": "userName",
            "type": "string"
        },
        {
            "name": "storeId",
            "baseName": "storeId",
            "type": "number"
        },
        {
            "name": "storeName",
            "baseName": "storeName",
            "type": "string"
        },
        {
            "name": "dispatcherId",
            "baseName": "dispatcherId",
            "type": "number"
        },
        {
            "name": "dispatcherName",
            "baseName": "dispatcherName",
            "type": "string"
        },
        {
            "name": "phone",
            "baseName": "phone",
            "type": "string"
        },
        {
            "name": "address",
            "baseName": "address",
            "type": "string"
        },
        {
            "name": "consignee",
            "baseName": "consignee",
            "type": "string"
        },
        {
            "name": "totalNum",
            "baseName": "totalNum",
            "type": "number"
        },
        {
            "name": "totalPrice",
            "baseName": "totalPrice",
            "type": "string"
        },
        {
            "name": "isPaid",
            "baseName": "isPaid",
            "type": "boolean"
        },
        {
            "name": "backIntegral",
            "baseName": "backIntegral",
            "type": "number"
        },
        {
            "name": "payTime",
            "baseName": "payTime",
            "type": "Date"
        },
        {
            "name": "payType",
            "baseName": "payType",
            "type": "string"
        },
        {
            "name": "origin",
            "baseName": "origin",
            "type": "number"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "number"
        },
        {
            "name": "refundImage",
            "baseName": "refundImage",
            "type": "string"
        },
        {
            "name": "refundReason",
            "baseName": "refundReason",
            "type": "string"
        },
        {
            "name": "refundRefuse",
            "baseName": "refundRefuse",
            "type": "string"
        },
        {
            "name": "refundTime",
            "baseName": "refundTime",
            "type": "Date"
        },
        {
            "name": "refundPrice",
            "baseName": "refundPrice",
            "type": "string"
        },
        {
            "name": "orderType",
            "baseName": "orderType",
            "type": "number"
        },
        {
            "name": "chargePrice",
            "baseName": "chargePrice",
            "type": "string"
        },
        {
            "name": "mark",
            "baseName": "mark",
            "type": "string"
        },
        {
            "name": "deliveryType",
            "baseName": "deliveryType",
            "type": "number"
        },
        {
            "name": "distributionTime",
            "baseName": "distributionTime",
            "type": "Date"
        },
        {
            "name": "createAt",
            "baseName": "createAt",
            "type": "Date"
        },
        {
            "name": "updateAt",
            "baseName": "updateAt",
            "type": "Date"
        }    ];

    static getAttributeTypeMap() {
        return FsOrder.attributeTypeMap;
    }
}

