/**
 * 社区生鲜
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';

export class FsStock {
    /**
    * ID
    */
    'id'?: number | null;
    /**
    * 商品id
    */
    'goodsId': number;
    /**
    * 进货、出货量
    */
    'number': number;
    /**
    * 类型，0进货、1出货
    */
    'type': number;
    /**
    * 备注
    */
    'remark'?: string | null;
    /**
    * 创建时间
    */
    'createAt'?: Date | null;
    /**
    * 更新时间
    */
    'updateAt'?: Date | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "goodsId",
            "baseName": "goodsId",
            "type": "number"
        },
        {
            "name": "number",
            "baseName": "number",
            "type": "number"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "number"
        },
        {
            "name": "remark",
            "baseName": "remark",
            "type": "string"
        },
        {
            "name": "createAt",
            "baseName": "createAt",
            "type": "Date"
        },
        {
            "name": "updateAt",
            "baseName": "updateAt",
            "type": "Date"
        }    ];

    static getAttributeTypeMap() {
        return FsStock.attributeTypeMap;
    }
}

