/**
 * 社区生鲜
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';

export class FsUser {
    /**
    * ID
    */
    'id'?: number | null;
    /**
    * openid
    */
    'openid': string;
    /**
    * unionId
    */
    'unionId'?: string | null;
    /**
    * appid
    */
    'appid': string;
    /**
    * 昵称
    */
    'nickName': string;
    /**
    * 头像地址
    */
    'avatarUrl'?: string | null;
    /**
    * 手机号码
    */
    'phoneNumber': string;
    /**
    * 性别，1为男，0为女
    */
    'gender': number;
    /**
    * 积分
    */
    'integral': number;
    /**
    * 余额
    */
    'balance': string;
    /**
    * 状态，1为正常、2为禁用
    */
    'status': number;
    /**
    * 创建时间
    */
    'createAt'?: Date | null;
    /**
    * 更新时间
    */
    'updateAt'?: Date | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "openid",
            "baseName": "openid",
            "type": "string"
        },
        {
            "name": "unionId",
            "baseName": "unionId",
            "type": "string"
        },
        {
            "name": "appid",
            "baseName": "appid",
            "type": "string"
        },
        {
            "name": "nickName",
            "baseName": "nickName",
            "type": "string"
        },
        {
            "name": "avatarUrl",
            "baseName": "avatarUrl",
            "type": "string"
        },
        {
            "name": "phoneNumber",
            "baseName": "phoneNumber",
            "type": "string"
        },
        {
            "name": "gender",
            "baseName": "gender",
            "type": "number"
        },
        {
            "name": "integral",
            "baseName": "integral",
            "type": "number"
        },
        {
            "name": "balance",
            "baseName": "balance",
            "type": "string"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "number"
        },
        {
            "name": "createAt",
            "baseName": "createAt",
            "type": "Date"
        },
        {
            "name": "updateAt",
            "baseName": "updateAt",
            "type": "Date"
        }    ];

    static getAttributeTypeMap() {
        return FsUser.attributeTypeMap;
    }
}

