/**
 * 社区生鲜
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';
import { FsGoods } from './fsGoods';
import { FsGoodsLabel } from './fsGoodsLabel';

export class Goods {
    /**
    * 商品信息
    */
    'goods': FsGoods;
    /**
    * 标签信息
    */
    'label': Array<FsGoodsLabel>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "goods",
            "baseName": "goods",
            "type": "FsGoods"
        },
        {
            "name": "label",
            "baseName": "label",
            "type": "Array<FsGoodsLabel>"
        }    ];

    static getAttributeTypeMap() {
        return Goods.attributeTypeMap;
    }
}

