/**
 * 社区生鲜
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';

export class MetaVo {
    'icon'?: string;
    'isAffix'?: boolean;
    'isHide'?: boolean;
    'isIframe'?: boolean;
    'isKeepAlive'?: boolean;
    'isLink'?: boolean;
    'title'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "icon",
            "baseName": "icon",
            "type": "string"
        },
        {
            "name": "isAffix",
            "baseName": "isAffix",
            "type": "boolean"
        },
        {
            "name": "isHide",
            "baseName": "isHide",
            "type": "boolean"
        },
        {
            "name": "isIframe",
            "baseName": "isIframe",
            "type": "boolean"
        },
        {
            "name": "isKeepAlive",
            "baseName": "isKeepAlive",
            "type": "boolean"
        },
        {
            "name": "isLink",
            "baseName": "isLink",
            "type": "boolean"
        },
        {
            "name": "title",
            "baseName": "title",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return MetaVo.attributeTypeMap;
    }
}

