/**
 * 社区生鲜
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';

export class OrderChange {
    /**
    * 订单id
    */
    'orderId': number;
    /**
    * 支付方式，如微信支付、现金支付、余额支付等
    */
    'payType': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "orderId",
            "baseName": "orderId",
            "type": "number"
        },
        {
            "name": "payType",
            "baseName": "payType",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return OrderChange.attributeTypeMap;
    }
}

