/**
 * 社区生鲜
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';
import { OrderItem } from './orderItem';

export class OrderDto {
    /**
    * 门店id
    */
    'storeId': number;
    /**
    * 收货人
    */
    'consignee': string;
    /**
    * 地址
    */
    'address': string;
    /**
    * 联系电话
    */
    'phone': string;
    /**
    * 配送时间
    */
    'distributionTime': Date;
    /**
    * 支付方式，如微信支付、现金支付、余额支付、积分支付等
    */
    'payType': string;
    /**
    * 送货方式，1门店配送、2到店自提、3第三方配送
    */
    'deliveryType': number;
    /**
    * 订单来源，1小程序商城、2人工收银台、3自助收银台
    */
    'origin': number;
    /**
    * 订单备注
    */
    'mark'?: string | null;
    /**
    * 订单项目
    */
    'item': Array<OrderItem>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "storeId",
            "baseName": "storeId",
            "type": "number"
        },
        {
            "name": "consignee",
            "baseName": "consignee",
            "type": "string"
        },
        {
            "name": "address",
            "baseName": "address",
            "type": "string"
        },
        {
            "name": "phone",
            "baseName": "phone",
            "type": "string"
        },
        {
            "name": "distributionTime",
            "baseName": "distributionTime",
            "type": "Date"
        },
        {
            "name": "payType",
            "baseName": "payType",
            "type": "string"
        },
        {
            "name": "deliveryType",
            "baseName": "deliveryType",
            "type": "number"
        },
        {
            "name": "origin",
            "baseName": "origin",
            "type": "number"
        },
        {
            "name": "mark",
            "baseName": "mark",
            "type": "string"
        },
        {
            "name": "item",
            "baseName": "item",
            "type": "Array<OrderItem>"
        }    ];

    static getAttributeTypeMap() {
        return OrderDto.attributeTypeMap;
    }
}

