/**
 * 社区生鲜
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';

export class OrderRefundDto {
    /**
    * 订单id
    */
    'id': number;
    /**
    * 退款金额
    */
    'refundPrice': number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "refundPrice",
            "baseName": "refundPrice",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return OrderRefundDto.attributeTypeMap;
    }
}

