/**
 * 社区生鲜
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';

export class Store {
    'id'?: number | null;
    /**
    * 店长id
    */
    'userId': number;
    /**
    * 门店名称
    */
    'name': string;
    /**
    * 简介
    */
    'introduction': string;
    /**
    * 手机号码
    */
    'phone': string;
    /**
    * 省市区
    */
    'address': string;
    /**
    * 详细地址
    */
    'addressDetail': string;
    /**
    * 门店图片
    */
    'image': string;
    /**
    * 纬度
    */
    'latitude': string;
    /**
    * 经度
    */
    'longitude': string;
    /**
    * 社区名称（小区名称）
    */
    'communityName': string;
    /**
    * 核销有效日期
    */
    'validTime'?: string | null;
    /**
    * 是否营业
    */
    'isShow': boolean;
    /**
    * 营业起始时间（HH:mm）
    */
    'dayTimeEnd': string;
    /**
    * 营业结束时间（HH:mm）
    */
    'dayTimeStart': string;
    /**
    * 每星期营业，格式如：0,1（星期天，星期一）
    */
    'dayWeek': string;
    /**
    * 核销起始时间
    */
    'validTimeStart'?: Date | null;
    /**
    * 核销结束时间
    */
    'validTimeEnd'?: Date | null;
    /**
    * 配送方式，是数组用,分割（1门店配送、2自提、3第三方配送）
    */
    'distributionWay': string;
    /**
    * 创建时间
    */
    'createAt'?: Date | null;
    /**
    * 更新时间
    */
    'updateAt'?: Date | null;
    /**
    * 距离
    */
    'distance': number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "userId",
            "baseName": "userId",
            "type": "number"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "introduction",
            "baseName": "introduction",
            "type": "string"
        },
        {
            "name": "phone",
            "baseName": "phone",
            "type": "string"
        },
        {
            "name": "address",
            "baseName": "address",
            "type": "string"
        },
        {
            "name": "addressDetail",
            "baseName": "addressDetail",
            "type": "string"
        },
        {
            "name": "image",
            "baseName": "image",
            "type": "string"
        },
        {
            "name": "latitude",
            "baseName": "latitude",
            "type": "string"
        },
        {
            "name": "longitude",
            "baseName": "longitude",
            "type": "string"
        },
        {
            "name": "communityName",
            "baseName": "communityName",
            "type": "string"
        },
        {
            "name": "validTime",
            "baseName": "validTime",
            "type": "string"
        },
        {
            "name": "isShow",
            "baseName": "isShow",
            "type": "boolean"
        },
        {
            "name": "dayTimeEnd",
            "baseName": "dayTimeEnd",
            "type": "string"
        },
        {
            "name": "dayTimeStart",
            "baseName": "dayTimeStart",
            "type": "string"
        },
        {
            "name": "dayWeek",
            "baseName": "dayWeek",
            "type": "string"
        },
        {
            "name": "validTimeStart",
            "baseName": "validTimeStart",
            "type": "Date"
        },
        {
            "name": "validTimeEnd",
            "baseName": "validTimeEnd",
            "type": "Date"
        },
        {
            "name": "distributionWay",
            "baseName": "distributionWay",
            "type": "string"
        },
        {
            "name": "createAt",
            "baseName": "createAt",
            "type": "Date"
        },
        {
            "name": "updateAt",
            "baseName": "updateAt",
            "type": "Date"
        },
        {
            "name": "distance",
            "baseName": "distance",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return Store.attributeTypeMap;
    }
}

