/**
 * 社区生鲜
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';

export class TotalVo {
    /**
    * 待付款
    */
    'watingPay': number;
    /**
    * 待发货
    */
    'waitingDeliver': number;
    /**
    * 待发货
    */
    'waitingReceipt': number;
    /**
    * 已完成
    */
    'completed': number;
    /**
    * 退款/售后
    */
    'refund': number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "watingPay",
            "baseName": "watingPay",
            "type": "number"
        },
        {
            "name": "waitingDeliver",
            "baseName": "waitingDeliver",
            "type": "number"
        },
        {
            "name": "waitingReceipt",
            "baseName": "waitingReceipt",
            "type": "number"
        },
        {
            "name": "completed",
            "baseName": "completed",
            "type": "number"
        },
        {
            "name": "refund",
            "baseName": "refund",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return TotalVo.attributeTypeMap;
    }
}

